//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computator.NET.UI.Menus.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Computator.NET.UI.Menus.Commands.MenuStrings", typeof(MenuStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        public static string aboutToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Constants.
        /// </summary>
        public static string constantsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("constantsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string copyToolStripButton_Text {
            get {
                return ResourceManager.GetString("copyToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy          Ctrl+C.
        /// </summary>
        public static string copyToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("copyToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ut.
        /// </summary>
        public static string cutToolStripButton_Text {
            get {
                return ResourceManager.GetString("cutToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t             Ctrl+X.
        /// </summary>
        public static string cutToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("cutToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string editToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("editToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Elementary functions.
        /// </summary>
        public static string elementaryFunctionsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("elementaryFunctionsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string exitToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("exitToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponent    Shift+6.
        /// </summary>
        public static string exponentiationToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("exponentiationToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fi&amp;le.
        /// </summary>
        public static string fileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string fullscreenToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("fullscreenToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Functions.
        /// </summary>
        public static string functionsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("functionsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He&amp;lp.
        /// </summary>
        public static string helpToolStripButton_Text {
            get {
                return ResourceManager.GetString("helpToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string helpToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("helpToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Mathematical constants.
        /// </summary>
        public static string mathematicalConstantsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("mathematicalConstantsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        public static string newToolStripButton_Text {
            get {
                return ResourceManager.GetString("newToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        public static string newToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("newToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        public static string openToolStripButton_Text {
            get {
                return ResourceManager.GetString("openToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        public static string openToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("openToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        public static string optionsToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("optionsToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        public static string pasteToolStripButton_Text {
            get {
                return ResourceManager.GetString("pasteToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste          Ctrl+V.
        /// </summary>
        public static string pasteToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("pasteToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Physical constants.
        /// </summary>
        public static string physicalConstantsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("physicalConstantsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pre&amp;view.
        /// </summary>
        public static string printPreviewToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("printPreviewToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        public static string printToolStripButton_Text {
            get {
                return ResourceManager.GetString("printToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        public static string printToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("printToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo          Ctrl+Y.
        /// </summary>
        public static string redoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("redoToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string runToolStripButton_Text {
            get {
                return ResourceManager.GetString("runToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As.
        /// </summary>
        public static string saveAsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveAsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string saveToolStripButton_Text {
            get {
                return ResourceManager.GetString("saveToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string saveToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All    Ctrl+A.
        /// </summary>
        public static string selectAllToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("selectAllToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Special functions.
        /// </summary>
        public static string specialFunctionsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("specialFunctionsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        public static string toolsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("toolsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT.
        /// </summary>
        public static string toolStripMenuItem31_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem31.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Fourier Transform.
        /// </summary>
        public static string toolStripMenuItem31_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripMenuItem31.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFFT.
        /// </summary>
        public static string toolStripMenuItem32_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem32.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Fast Fourier Transform.
        /// </summary>
        public static string toolStripMenuItem32_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripMenuItem32.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DST.
        /// </summary>
        public static string toolStripMenuItem33_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem33.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete Sine Transform.
        /// </summary>
        public static string toolStripMenuItem33_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripMenuItem33.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDST.
        /// </summary>
        public static string toolStripMenuItem34_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem34.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Discrete Sine Transform.
        /// </summary>
        public static string toolStripMenuItem34_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripMenuItem34.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCT.
        /// </summary>
        public static string toolStripMenuItem35_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem35.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete Cosine Transform.
        /// </summary>
        public static string toolStripMenuItem35_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripMenuItem35.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDCT.
        /// </summary>
        public static string toolStripMenuItem36_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem36.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Discrete Cosine Transform.
        /// </summary>
        public static string toolStripMenuItem36_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripMenuItem36.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FHT.
        /// </summary>
        public static string toolStripMenuItem37_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem37.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Hilbert Transform.
        /// </summary>
        public static string toolStripMenuItem37_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripMenuItem37.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFHT.
        /// </summary>
        public static string toolStripMenuItem38_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem38.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Fast Hilbert Transform.
        /// </summary>
        public static string toolStripMenuItem38_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripMenuItem38.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHT.
        /// </summary>
        public static string toolStripMenuItem39_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem39.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete Hartley Transform.
        /// </summary>
        public static string toolStripMenuItem39_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripMenuItem39.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Benchmark.
        /// </summary>
        public static string toolStripMenuItem40_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem40.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Logs.
        /// </summary>
        public static string toolStripMenuItem41_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem41.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string toolStripMenuItem42_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem42.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Features.
        /// </summary>
        public static string toolStripMenuItem43_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem43.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Thanks to.
        /// </summary>
        public static string toolStripMenuItem44_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem44.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Changelog.
        /// </summary>
        public static string toolStripMenuItem45_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem45.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bug reporting.
        /// </summary>
        public static string toolStripMenuItem46_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem46.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tran&amp;sform.
        /// </summary>
        public static string transformToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("transformToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo         Ctrl+Z.
        /// </summary>
        public static string undoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("undoToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
