//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computator.NET.Charting.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditChartWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditChartWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Computator.NET.Charting.Localization.EditChartWindow", typeof(EditChartWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string button2_Text {
            get {
                return ResourceManager.GetString("button2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart title.
        /// </summary>
        internal static string button3_Text {
            get {
                return ResourceManager.GetString("button3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y axes.
        /// </summary>
        internal static string button4_Text {
            get {
                return ResourceManager.GetString("button4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        internal static string button5_Text {
            get {
                return ResourceManager.GetString("button5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical values.
        /// </summary>
        internal static string button6_Text {
            get {
                return ResourceManager.GetString("button6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string fontsGroupBox_Text {
            get {
                return ResourceManager.GetString("fontsGroupBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axes values.
        /// </summary>
        internal static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string groupBox2_Text {
            get {
                return ResourceManager.GetString("groupBox2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        internal static string groupBox3_Text {
            get {
                return ResourceManager.GetString("groupBox3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x minimum.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label 3.
        /// </summary>
        internal static string label10_Text {
            get {
                return ResourceManager.GetString("label10.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label 4.
        /// </summary>
        internal static string label11_Text {
            get {
                return ResourceManager.GetString("label11.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x step.
        /// </summary>
        internal static string label12_Text {
            get {
                return ResourceManager.GetString("label12.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y step.
        /// </summary>
        internal static string label13_Text {
            get {
                return ResourceManager.GetString("label13.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line thickness.
        /// </summary>
        internal static string label14_Text {
            get {
                return ResourceManager.GetString("label14.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to px.
        /// </summary>
        internal static string label15_Text {
            get {
                return ResourceManager.GetString("label15.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to px.
        /// </summary>
        internal static string label16_Text {
            get {
                return ResourceManager.GetString("label16.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points size.
        /// </summary>
        internal static string label17_Text {
            get {
                return ResourceManager.GetString("label17.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x maximum.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y maximum.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y minimum.
        /// </summary>
        internal static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y label.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x label.
        /// </summary>
        internal static string label6_Text {
            get {
                return ResourceManager.GetString("label6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chart title.
        /// </summary>
        internal static string label7_Text {
            get {
                return ResourceManager.GetString("label7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label 1.
        /// </summary>
        internal static string label8_Text {
            get {
                return ResourceManager.GetString("label8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label 2.
        /// </summary>
        internal static string label9_Text {
            get {
                return ResourceManager.GetString("label9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show legend?.
        /// </summary>
        internal static string legendVisible_Text {
            get {
                return ResourceManager.GetString("legendVisible.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit chart.
        /// </summary>
        internal static string this_Text {
            get {
                return ResourceManager.GetString("this_Text", resourceCulture);
            }
        }
    }
}
