//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computator.NET.Charting.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditChart3DWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditChart3DWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Computator.NET.Charting.Localization.EditChart3DWindow", typeof(EditChart3DWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit font.
        /// </summary>
        internal static string button2_Text {
            get {
                return ResourceManager.GetString("button2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancelButton_Text {
            get {
                return ResourceManager.GetString("cancelButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal axes.
        /// </summary>
        internal static string equalAxesCheckBox_Text {
            get {
                return ResourceManager.GetString("equalAxesCheckBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axes of coordinate system.
        /// </summary>
        internal static string groupBox2_Text {
            get {
                return ResourceManager.GetString("groupBox2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Labels.
        /// </summary>
        internal static string groupBox3_Text {
            get {
                return ResourceManager.GetString("groupBox3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-axis Label.
        /// </summary>
        internal static string groupBox4_Text {
            get {
                return ResourceManager.GetString("groupBox4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-axis Label.
        /// </summary>
        internal static string groupBox5_Text {
            get {
                return ResourceManager.GetString("groupBox5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-axis Label.
        /// </summary>
        internal static string groupBox6_Text {
            get {
                return ResourceManager.GetString("groupBox6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels distance.
        /// </summary>
        internal static string groupBox7_Text {
            get {
                return ResourceManager.GetString("groupBox7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axes values.
        /// </summary>
        internal static string groupBox8_Text {
            get {
                return ResourceManager.GetString("groupBox8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale:.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y (pixels):.
        /// </summary>
        internal static string label10_Text {
            get {
                return ResourceManager.GetString("label10.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of axis labels:.
        /// </summary>
        internal static string label11_Text {
            get {
                return ResourceManager.GetString("label11.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font of axis labels:.
        /// </summary>
        internal static string label12_Text {
            get {
                return ResourceManager.GetString("label12.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart3D Type:.
        /// </summary>
        internal static string label13_Text {
            get {
                return ResourceManager.GetString("label13.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point size:.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x minimum.
        /// </summary>
        internal static string label20_Text {
            get {
                return ResourceManager.GetString("label20.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x maximum.
        /// </summary>
        internal static string label21_Text {
            get {
                return ResourceManager.GetString("label21.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y minimum.
        /// </summary>
        internal static string label22_Text {
            get {
                return ResourceManager.GetString("label22.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y maximum.
        /// </summary>
        internal static string label23_Text {
            get {
                return ResourceManager.GetString("label23.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axes color:.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color:.
        /// </summary>
        internal static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In units:.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label text:.
        /// </summary>
        internal static string label6_Text {
            get {
                return ResourceManager.GetString("label6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label text:.
        /// </summary>
        internal static string label7_Text {
            get {
                return ResourceManager.GetString("label7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x (pixels):.
        /// </summary>
        internal static string label8_Text {
            get {
                return ResourceManager.GetString("label8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label text:.
        /// </summary>
        internal static string label9_Text {
            get {
                return ResourceManager.GetString("label9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis labels visible?.
        /// </summary>
        internal static string labelsVisibilityCheckBox_Text {
            get {
                return ResourceManager.GetString("labelsVisibilityCheckBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Chart 3D.
        /// </summary>
        internal static string this_Text {
            get {
                return ResourceManager.GetString("this_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axes visible?.
        /// </summary>
        internal static string visibleAxesCheckBox_Text {
            get {
                return ResourceManager.GetString("visibleAxesCheckBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active?.
        /// </summary>
        internal static string xActiveCheckBox_Text {
            get {
                return ResourceManager.GetString("xActiveCheckBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active?.
        /// </summary>
        internal static string yActiveCheckBox_Text {
            get {
                return ResourceManager.GetString("yActiveCheckBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active?.
        /// </summary>
        internal static string zActiveCheckBox_Text {
            get {
                return ResourceManager.GetString("zActiveCheckBox.Text", resourceCulture);
            }
        }
    }
}
