//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computator.NET.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Computator.NET.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to chart.
        /// </summary>
        internal static string AddToChart {
            get {
                return ResourceManager.GetString("AddToChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad syntax.
        /// </summary>
        internal static string BadSyntax {
            get {
                return ResourceManager.GetString("BadSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beta testers.
        /// </summary>
        internal static string betaTesters {
            get {
                return ResourceManager.GetString("betaTesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source:.
        /// </summary>
        internal static string BrBrISourceBrAHref {
            get {
                return ResourceManager.GetString("BrBrISourceBrAHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug reporting.
        /// </summary>
        internal static string BugReporting {
            get {
                return ResourceManager.GetString("BugReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled!.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console output:.
        /// </summary>
        internal static string ConsoleOutput {
            get {
                return ResourceManager.GetString("ConsoleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details: .
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw chart.
        /// </summary>
        internal static string DrawChart {
            get {
                return ResourceManager.GetString("DrawChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in expression syntax. One of used functions does not exist / is incompatible with given arguments or you just made a mistake writing expression..
        /// </summary>
        internal static string ErrorInExpressionSyntaxOneOfUsedFunctionsDoesNotExistIsIncompatibleWithGivenArgumentsOrYouJustMadeAMistakeWritingExpression {
            get {
                return ResourceManager.GetString("ErrorInExpressionSyntaxOneOfUsedFunctionsDoesNotExistIsIncompatibleWithGivenArgum" +
                        "entsOrYouJustMadeAMistakeWritingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features:.
        /// </summary>
        internal static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Real and complex functions charts
        /// - Real and complex calculator
        /// - Real functions numerical calculations including different methods
        /// - Over 107 Elementary functions
        /// - Over 141 Special functions
        /// - Over 21 Matrix functions and operations
        /// - Scripting language with power to easy computations including matrices
        /// - You can declare your own custom functions with scripting language.
        /// </summary>
        internal static string featuresInclude {
            get {
                return ResourceManager.GetString("featuresInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For chosen values one (or more) of the functions in your expression cannot convergence
        ///.
        /// </summary>
        internal static string ForChosenValuesOneOrMoreOfTheFunctionsInYourExpressionCannotConvergence {
            get {
                return ResourceManager.GetString("ForChosenValuesOneOrMoreOfTheFunctionsInYourExpressionCannotConvergence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given ε is not valid..
        /// </summary>
        internal static string GivenΕIsNotValid {
            get {
                return ResourceManager.GetString("GivenΕIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given ε is not valid. ε should be small positive number..
        /// </summary>
        internal static string GivenΕIsNotValidΕShouldBeSmallPositiveNumber {
            get {
                return ResourceManager.GetString("GivenΕIsNotValidΕShouldBeSmallPositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression should not be empty!.
        /// </summary>
        internal static string GUI_addToChartButton_Click_Expression_should_not_be_empty_ {
            get {
                return ResourceManager.GetString("GUI_addToChartButton_Click_Expression_should_not_be_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Check &quot;Real : f(x)&quot; mode.
        /// </summary>
        internal static string GUI_numericalOperationButton_Click__Check__Real___f_x___mode {
            get {
                return ResourceManager.GetString("GUI_numericalOperationButton_Click__Check__Real___f_x___mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Real mode is supported in Numerical calculations right now, more to come in next versions!.
        /// </summary>
        internal static string GUI_numericalOperationButton_Click_Only_Real_mode_is_supported_in_Numerical_calculations_right_now__more_to_come_in_next_versions_ {
            get {
                return ResourceManager.GetString("GUI_numericalOperationButton_Click_Only_Real_mode_is_supported_in_Numerical_calcu" +
                        "lations_right_now__more_to_come_in_next_versions_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string GUI_numericalOperationButton_Click_Warning_ {
            get {
                return ResourceManager.GetString("GUI_numericalOperationButton_Click_Warning_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///It&apos;s features include:.
        /// </summary>
        internal static string ItSFeaturesInclude {
            get {
                return ResourceManager.GetString("ItSFeaturesInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to libraries used.
        /// </summary>
        internal static string librariesUsed {
            get {
                return ResourceManager.GetString("librariesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math functions calculation speed test cancelled by user..
        /// </summary>
        internal static string MathFunctionsCalculationSpeedTestCancelledByUser {
            get {
                return ResourceManager.GetString("MathFunctionsCalculationSpeedTestCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math functions calculation speed test done succesfully! Check out your points results!.
        /// </summary>
        internal static string MathFunctionsCalculationSpeedTestDoneSuccesfullyCheckOutYourPointsResults {
            get {
                return ResourceManager.GetString("MathFunctionsCalculationSpeedTestDoneSuccesfullyCheckOutYourPointsResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocation speed test done succesfully, check out your points result.
        /// </summary>
        internal static string MemoryAllocationSpeedTestDoneSuccesfullyCheckOutYourPointsResult {
            get {
                return ResourceManager.GetString("MemoryAllocationSpeedTestDoneSuccesfullyCheckOutYourPointsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocation speed test cancelled by user.
        /// </summary>
        internal static string memoryTestBackgroundWorker_RunWorkerCompleted {
            get {
                return ResourceManager.GetString("memoryTestBackgroundWorker_RunWorkerCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details: .
        /// </summary>
        internal static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function to invoke.
        /// </summary>
        internal static string NoFunctionToInvoke {
            get {
                return ResourceManager.GetString("NoFunctionToInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other contributors.
        /// </summary>
        internal static string otherContributors {
            get {
                return ResourceManager.GetString("otherContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report any bugs to Paweł Troka - ptroka@fizyka.dk.
        /// </summary>
        internal static string PleaseReportAnyBugsToPawełTrokaPtrokaFizykaDk {
            get {
                return ResourceManager.GetString("PleaseReportAnyBugsToPawełTrokaPtrokaFizykaDk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Points!.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  result: .
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to:.
        /// </summary>
        internal static string SpecialThanksTo {
            get {
                return ResourceManager.GetString("SpecialThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translators.
        /// </summary>
        internal static string translators {
            get {
                return ResourceManager.GetString("translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   |  X/Y ratio = {0}  |.
        /// </summary>
        internal static string XYRatio0 {
            get {
                return ResourceManager.GetString("XYRatio0", resourceCulture);
            }
        }
    }
}
