//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computator.NET.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Computator.NET.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to chart.
        /// </summary>
        internal static string AddToChart {
            get {
                return ResourceManager.GetString("AddToChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad syntax.
        /// </summary>
        internal static string BadSyntax {
            get {
                return ResourceManager.GetString("BadSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beta testers.
        /// </summary>
        internal static string betaTesters {
            get {
                return ResourceManager.GetString("betaTesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source:.
        /// </summary>
        internal static string BrBrISourceBrAHref {
            get {
                return ResourceManager.GetString("BrBrISourceBrAHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug reporting.
        /// </summary>
        internal static string BugReporting {
            get {
                return ResourceManager.GetString("BugReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled!.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console output:.
        /// </summary>
        internal static string ConsoleOutput {
            get {
                return ResourceManager.GetString("ConsoleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details: .
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        internal static string DirectoryTree_DirectoryTree_Delete_file {
            get {
                return ResourceManager.GetString("DirectoryTree_DirectoryTree_Delete_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        internal static string DirectoryTree_DirectoryTree_New_file {
            get {
                return ResourceManager.GetString("DirectoryTree_DirectoryTree_New_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file.
        /// </summary>
        internal static string DirectoryTree_DirectoryTree_Rename_file {
            get {
                return ResourceManager.GetString("DirectoryTree_DirectoryTree_Rename_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid label.
        ///.
        /// </summary>
        internal static string DirectoryTree_treeView1_AfterLabelEdit_ {
            get {
                return ResourceManager.GetString("DirectoryTree_treeView1_AfterLabelEdit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label edit error.
        /// </summary>
        internal static string DirectoryTree_treeView1_AfterLabelEdit_Node_Label_Edit {
            get {
                return ResourceManager.GetString("DirectoryTree_treeView1_AfterLabelEdit_Node_Label_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invalid characters are: &apos;@&apos;,&apos;.&apos;, &apos;,&apos;, &apos;!&apos;.
        /// </summary>
        internal static string DirectoryTree_treeView1_AfterLabelEdit_The_invalid_characters {
            get {
                return ResourceManager.GetString("DirectoryTree_treeView1_AfterLabelEdit_The_invalid_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label cannot be blank.
        /// </summary>
        internal static string DirectoryTree_treeView1_AfterLabelEdit_The_label_cannot_be_blank {
            get {
                return ResourceManager.GetString("DirectoryTree_treeView1_AfterLabelEdit_The_label_cannot_be_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewFile.
        /// </summary>
        internal static string DocumentsTabControl_AddTab_NewFile {
            get {
                return ResourceManager.GetString("DocumentsTabControl_AddTab_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone tab.
        /// </summary>
        internal static string DocumentsTabControl_InitializeComponent_Clone_tab {
            get {
                return ResourceManager.GetString("DocumentsTabControl_InitializeComponent_Clone_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close other tabs.
        /// </summary>
        internal static string DocumentsTabControl_InitializeComponent_Close_other_tabs {
            get {
                return ResourceManager.GetString("DocumentsTabControl_InitializeComponent_Close_other_tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab.
        /// </summary>
        internal static string DocumentsTabControl_InitializeComponent_Close_tab {
            get {
                return ResourceManager.GetString("DocumentsTabControl_InitializeComponent_Close_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tabs to the left.
        /// </summary>
        internal static string DocumentsTabControl_InitializeComponent_Close_tabs_to_the_left {
            get {
                return ResourceManager.GetString("DocumentsTabControl_InitializeComponent_Close_tabs_to_the_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tabs to the right.
        /// </summary>
        internal static string DocumentsTabControl_InitializeComponent_Close_tabs_to_the_right {
            get {
                return ResourceManager.GetString("DocumentsTabControl_InitializeComponent_Close_tabs_to_the_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tab.
        /// </summary>
        internal static string DocumentsTabControl_InitializeComponent_New_tab {
            get {
                return ResourceManager.GetString("DocumentsTabControl_InitializeComponent_New_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw chart.
        /// </summary>
        internal static string DrawChart {
            get {
                return ResourceManager.GetString("DrawChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in expression syntax. One of used functions does not exist / is incompatible with given arguments or you just made a mistake writing expression..
        /// </summary>
        internal static string ErrorInExpressionSyntaxOneOfUsedFunctionsDoesNotExistIsIncompatibleWithGivenArgumentsOrYouJustMadeAMistakeWritingExpression {
            get {
                return ResourceManager.GetString("ErrorInExpressionSyntaxOneOfUsedFunctionsDoesNotExistIsIncompatibleWithGivenArgum" +
                        "entsOrYouJustMadeAMistakeWritingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features:.
        /// </summary>
        internal static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Real and complex functions charts
        ///
        /// - Real and complex calculator
        ///
        /// - Real functions numerical calculations including different methods
        ///
        /// - Over 107 Elementary functions
        ///
        /// - Over 141 Special functions
        ///
        /// - Over 21 Matrix functions and operations
        ///
        /// - Scripting language with power to easy computations including matrices
        ///
        /// - You can declare your own custom functions with scripting language.
        /// </summary>
        internal static string featuresInclude {
            get {
                return ResourceManager.GetString("featuresInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For chosen values one (or more) of the functions in your expression cannot convergence
        ///.
        /// </summary>
        internal static string ForChosenValuesOneOrMoreOfTheFunctionsInYourExpressionCannotConvergence {
            get {
                return ResourceManager.GetString("ForChosenValuesOneOrMoreOfTheFunctionsInYourExpressionCannotConvergence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given ε is not valid..
        /// </summary>
        internal static string GivenΕIsNotValid {
            get {
                return ResourceManager.GetString("GivenΕIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given ε is not valid. ε should be small positive number..
        /// </summary>
        internal static string GivenΕIsNotValidΕShouldBeSmallPositiveNumber {
            get {
                return ResourceManager.GetString("GivenΕIsNotValidΕShouldBeSmallPositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computator.NET is a special kind of numerical software that is fast and easy to use but not worse than others feature-wise..
        /// </summary>
        internal static string GlobalConfig_assemblyDescription_Computator_NET_is_a_special_kind_of_numerical_software_that_is_fast_and_easy_to_use_but_not_worse_than_others_feature_wise_ {
            get {
                return ResourceManager.GetString("GlobalConfig_assemblyDescription_Computator_NET_is_a_special_kind_of_numerical_so" +
                        "ftware_that_is_fast_and_easy_to_use_but_not_worse_than_others_feature_wise_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart3D classes are based on code from High performance WPF 3D Chart rev.6 application on license.
        /// </summary>
        internal static string GlobalConfig_others_Chart3D_classes_are_based_on_code_from_High_performance_WPF_3D_Chart_rev_6_application_on {
            get {
                return ResourceManager.GetString("GlobalConfig_others_Chart3D_classes_are_based_on_code_from_High_performance_WPF_3" +
                        "D_Chart_rev_6_application_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard algorithm for complex domain coloring.
        /// </summary>
        internal static string GlobalConfig_others_standard_algorithm_for_complex_domain_coloring {
            get {
                return ResourceManager.GetString("GlobalConfig_others_standard_algorithm_for_complex_domain_coloring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression should not be empty!.
        /// </summary>
        internal static string GUI_addToChartButton_Click_Expression_should_not_be_empty_ {
            get {
                return ResourceManager.GetString("GUI_addToChartButton_Click_Expression_should_not_be_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        internal static string GUI_changelogToolStripMenuItem_Click_Changelog {
            get {
                return ResourceManager.GetString("GUI_changelogToolStripMenuItem_Click_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Png Image (.png)|*.png|Gif Image (.gif)|*.gif|JPEG Image (.jpeg)|*.jpeg|Bitmap Image (.bmp)|*.bmp|Tiff Image (.tiff)|*.tiff|Wmf Image (.wmf)|*.wmf.
        /// </summary>
        internal static string GUI_exportChart3dToolStripMenuItem_Click_Image_FIlter {
            get {
                return ResourceManager.GetString("GUI_exportChart3dToolStripMenuItem_Click_Image_FIlter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have any logs yet..
        /// </summary>
        internal static string GUI_logsToolStripMenuItem_Click_You_dont_have_any_logs_yet_ {
            get {
                return ResourceManager.GetString("GUI_logsToolStripMenuItem_Click_You_dont_have_any_logs_yet_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Check &quot;Real : f(x)&quot; mode.
        /// </summary>
        internal static string GUI_numericalOperationButton_Click__Check__Real___f_x___mode {
            get {
                return ResourceManager.GetString("GUI_numericalOperationButton_Click__Check__Real___f_x___mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Real mode is supported in Numerical calculations right now, more to come in next versions!.
        /// </summary>
        internal static string GUI_numericalOperationButton_Click_Only_Real_mode_is_supported_in_Numerical_calculations_right_now__more_to_come_in_next_versions_ {
            get {
                return ResourceManager.GetString("GUI_numericalOperationButton_Click_Only_Real_mode_is_supported_in_Numerical_calcu" +
                        "lations_right_now__more_to_come_in_next_versions_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string GUI_numericalOperationButton_Click_Warning_ {
            get {
                return ResourceManager.GetString("GUI_numericalOperationButton_Click_Warning_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of steps should be small, default is 6.
        /// </summary>
        internal static string Integral_rombergMethod_Number_of_steps_should_be_small__default_is_6 {
            get {
                return ResourceManager.GetString("Integral_rombergMethod_Number_of_steps_should_be_small__default_is_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s features include:.
        /// </summary>
        internal static string ItSFeaturesInclude {
            get {
                return ResourceManager.GetString("ItSFeaturesInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to libraries used.
        /// </summary>
        internal static string librariesUsed {
            get {
                return ResourceManager.GetString("librariesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math functions calculation speed test cancelled by user..
        /// </summary>
        internal static string MathFunctionsCalculationSpeedTestCancelledByUser {
            get {
                return ResourceManager.GetString("MathFunctionsCalculationSpeedTestCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math functions calculation speed test done succesfully! Check out your points results!.
        /// </summary>
        internal static string MathFunctionsCalculationSpeedTestDoneSuccesfullyCheckOutYourPointsResults {
            get {
                return ResourceManager.GetString("MathFunctionsCalculationSpeedTestDoneSuccesfullyCheckOutYourPointsResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocation speed test done succesfully, check out your points result.
        /// </summary>
        internal static string MemoryAllocationSpeedTestDoneSuccesfullyCheckOutYourPointsResult {
            get {
                return ResourceManager.GetString("MemoryAllocationSpeedTestDoneSuccesfullyCheckOutYourPointsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocation speed test cancelled by user.
        /// </summary>
        internal static string memoryTestBackgroundWorker_RunWorkerCompleted {
            get {
                return ResourceManager.GetString("memoryTestBackgroundWorker_RunWorkerCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details: .
        /// </summary>
        internal static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function to invoke.
        /// </summary>
        internal static string NoFunctionToInvoke {
            get {
                return ResourceManager.GetString("NoFunctionToInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other contributors.
        /// </summary>
        internal static string otherContributors {
            get {
                return ResourceManager.GetString("otherContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report any bugs to Paweł Troka - ptroka@fizyka.dk.
        /// </summary>
        internal static string PleaseReportAnyBugsToPawełTrokaPtrokaFizykaDk {
            get {
                return ResourceManager.GetString("PleaseReportAnyBugsToPawełTrokaPtrokaFizykaDk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Points!.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Thread Exception.
        /// </summary>
        internal static string Program_Application_ThreadException_Unhandled_Thread_Exception {
            get {
                return ResourceManager.GetString("Program_Application_ThreadException_Unhandled_Thread_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled UI Exception.
        /// </summary>
        internal static string Program_CurrentDomain_UnhandledException_Unhandled_UI_Exception {
            get {
                return ResourceManager.GetString("Program_CurrentDomain_UnhandledException_Unhandled_UI_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  result: .
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to:.
        /// </summary>
        internal static string SpecialThanksTo {
            get {
                return ResourceManager.GetString("SpecialThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translators.
        /// </summary>
        internal static string translators {
            get {
                return ResourceManager.GetString("translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions &amp; Constants Details.
        /// </summary>
        internal static string WebBrowserForm_WebBrowserForm_Functions___Constants_Details {
            get {
                return ResourceManager.GetString("WebBrowserForm_WebBrowserForm_Functions___Constants_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   |  X/Y ratio = {0}  |.
        /// </summary>
        internal static string XYRatio0 {
            get {
                return ResourceManager.GetString("XYRatio0", resourceCulture);
            }
        }
    }
}
