//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computator.NET.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Globalization.CultureInfo Language {
            get {
                return ((global::System.Globalization.CultureInfo)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Scintilla")]
        public global::Computator.NET.DataTypes.SettingsTypes.CodeEditorType CodeEditor {
            get {
                return ((global::Computator.NET.DataTypes.SettingsTypes.CodeEditorType)(this["CodeEditor"]));
            }
            set {
                this["CodeEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::Computator.NET.DataTypes.SettingsTypes.FunctionsOrder FunctionsOrder {
            get {
                return ((global::Computator.NET.DataTypes.SettingsTypes.FunctionsOrder)(this["FunctionsOrder"]));
            }
            set {
                this["FunctionsOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::Computator.NET.DataTypes.SettingsTypes.TooltipType TooltipType {
            get {
                return ((global::Computator.NET.DataTypes.SettingsTypes.TooltipType)(this["TooltipType"]));
            }
            set {
                this["TooltipType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cambria, 15.75pt")]
        public global::System.Drawing.Font ExpressionFont {
            get {
                return ((global::System.Drawing.Font)(this["ExpressionFont"]));
            }
            set {
                this["ExpressionFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas, 12pt")]
        public global::System.Drawing.Font ScriptingFont {
            get {
                return ((global::System.Drawing.Font)(this["ScriptingFont"]));
            }
            set {
                this["ScriptingFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowReturnTypeInExpression {
            get {
                return ((bool)(this["ShowReturnTypeInExpression"]));
            }
            set {
                this["ShowReturnTypeInExpression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowParametersTypeInExpression {
            get {
                return ((bool)(this["ShowParametersTypeInExpression"]));
            }
            set {
                this["ShowParametersTypeInExpression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowReturnTypeInScripting {
            get {
                return ((bool)(this["ShowReturnTypeInScripting"]));
            }
            set {
                this["ShowReturnTypeInScripting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowParametersTypeInScripting {
            get {
                return ((bool)(this["ShowParametersTypeInScripting"]));
            }
            set {
                this["ShowParametersTypeInScripting"] = value;
            }
        }
    }
}
